# Generated by Django 2.0.2 on 2018-03-26 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chart_type', models.CharField(choices=[('ZX', 'LINE'), ('SD', 'SCATTER'), ('BT', 'PIE'), ('ZZ', 'BAR'), ('LD', 'RADAR'), ('3D', '3D')], max_length=2)),
                ('created_time', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField()),
                ('json_option', models.TextField()),
                ('chart_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyModel.Chart')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('datasourcebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MyModel.DataSourceBase')),
                ('data_type', models.CharField(choices=[('T', 'txt'), ('D', 'database')], max_length=1)),
                ('data', models.TextField()),
            ],
            bases=('MyModel.datasourcebase',),
        ),
        migrations.AddField(
            model_name='datasourcebase',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chart',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyModel.DataSource'),
        ),
    ]
