# Generated by Django 2.0.2 on 2018-03-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0002_auto_20180326_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='datasourcebase',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='datasourcebase',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
