# Generated by Django 2.0.2 on 2018-03-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0003_auto_20180326_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='chart_name',
            new_name='chart',
        ),
    ]
