# Generated by Django 2.0.2 on 2018-03-26 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyModel', '0004_auto_20180326_2038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='datasourcebase',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('name', 'chart')},
        ),
    ]
