# Generated by Django 2.0.2 on 2018-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0006_chart_cur_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='data_type',
            field=models.CharField(choices=[('T', 'txt'), ('E', 'excel')], max_length=1),
        ),
    ]
