# Generated by Django 2.0.2 on 2018-04-10 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0009_auto_20180408_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyModel.DataSet'),
        ),
    ]
