# Generated by Django 2.0.2 on 2018-04-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0011_dataset_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chart',
            name='cur_option',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='datasourcebase_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='datasourcebase',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='datasourcebase',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='option',
            name='chart',
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='DataSourceBase',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
