# Generated by Django 2.0.2 on 2018-04-11 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyModel', '0012_auto_20180410_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='testChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField()),
                ('cur_option', models.TextField()),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyModel.DataSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='testchart',
            unique_together={('user', 'name')},
        ),
    ]
