# Generated by Django 2.0.2 on 2018-05-08 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyModel', '0013_auto_20180411_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('backGroundOption', models.TextField()),
                ('chartSet', models.ManyToManyField(to='MyModel.testChart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data_type',
            field=models.CharField(choices=[('T', 'txt'), ('E', 'excel'), ('C', 'csv')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('name', 'user')},
        ),
    ]
