# Generated by Django 2.0.2 on 2018-05-27 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyModel', '0015_auto_20180523_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='miliTime',
            field=models.TextField(default=1527410037624),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='lastUpdated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 5, 27, 17, 13, 37, 46592)),
        ),
        migrations.AlterField(
            model_name='testchart',
            name='dataLastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 27, 17, 13, 37, 47569)),
        ),
    ]
